export const mapActionTypes = {
  FETCH_LOCATION_REQUEST: 'FETCH_LOCATION_REQUEST',
  FETCH_LOCATION_SUCCESS: 'FETCH_LOCATION_SUCCESS',
  FECTH_LOCATION_FAILED: 'FETCH_LOCATION_FAILED',
  SET_CURRENT_LOCATION: 'SET_CURRENT_LOCATION',
  CLEAR_LOCATIONS: 'CLEAR_LOCATIONS',
}